
export const clients = [
  {
    id: 'c1',
    nombres: 'Ana',
    apellidos: 'García',
    email: 'ana.garcia@example.com',
    telefono: '987654321',
    direccion: 'Calle Falsa 123',
    comuna: 'Santiago',
    region: 'Región Metropolitana',
    avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
    jobCount: 5,
    averageRating: 4.8,
    reviewsGiven: [
      { experto: 'Juan Pérez', rating: 5, comment: 'Excelente trabajo de plomería.' },
      { experto: 'María López', rating: 4, comment: 'Buen servicio de electricidad.' },
    ],
  },
  {
    id: 'c2',
    nombres: 'Pedro',
    apellidos: 'Martínez',
    email: 'pedro.martinez@example.com',
    telefono: '123456789',
    direccion: 'Avenida Siempre Viva 742',
    comuna: 'Providencia',
    region: 'Región Metropolitana',
    avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
    jobCount: 3,
    averageRating: 4.5,
    reviewsGiven: [
      { experto: 'Carlos Ruiz', rating: 5, comment: 'Muy profesional y rápido.' },
    ],
  },
];

export const jobs = [
  {
    id: 'j1',
    clientId: 'c1',
    titulo: 'Instalación de grifo de cocina',
    descripcion: 'Necesito un plomero para instalar un nuevo grifo en la cocina. El grifo ya está comprado.',
    categoria: 'Plomería',
    region: 'Región Metropolitana',
    provincia: 'Santiago',
    comuna: 'Santiago',
    presupuesto: 30000,
    fechaCreacion: '2024-06-20T10:00:00Z',
    estado: 'activo',
  },
  {
    id: 'j2',
    clientId: 'c2',
    titulo: 'Reparación de enchufe eléctrico',
    descripcion: 'Un enchufe en la sala de estar no funciona. Posiblemente un cable suelto.',
    categoria: 'Electricidad',
    region: 'Región Metropolitana',
    provincia: 'Santiago',
    comuna: 'Providencia',
    presupuesto: 20000,
    fechaCreacion: '2024-06-22T14:30:00Z',
    estado: 'activo',
  },
  {
    id: 'j3',
    clientId: 'c1',
    titulo: 'Pintar habitación pequeña',
    descripcion: 'Necesito pintar una habitación de 3x3 metros. Color blanco, incluye preparación de paredes.',
    categoria: 'Pintura',
    region: 'Región Metropolitana',
    provincia: 'Santiago',
    comuna: 'Ñuñoa',
    presupuesto: 50000,
    fechaCreacion: '2024-06-25T09:00:00Z',
    estado: 'activo',
  },
];

export const portfolioItems = [
  {
    id: 'pi1',
    expertoId: 'm1',
    title: 'Renovación completa de baño',
    description: 'Instalación de ducha empotrada, nuevo lavamanos y grifería premium. Trabajo terminado en 2 días.',
    category: 'Plomería',
    date: '2024-03-15',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80',
    reactions: { heart: 14, like: 9, clap: 6, dislike: 1 },
    reviews: [
      { id: 'r1', user: 'Ana García', userId: 'c1', comment: '¡Quedó impecable! Muy profesional y ordenado.', rating: 5, date: '2024-03-17' },
      { id: 'r2', user: 'Pedro Martínez', userId: 'c2', comment: 'Excelente trabajo, cumplió los plazos.', rating: 5, date: '2024-03-18' },
    ],
  },
  {
    id: 'pi2',
    expertoId: 'm1',
    title: 'Instalación de calefont a gas',
    description: 'Reemplazo de calefont antiguo por uno nuevo de bajo consumo. Incluye revisión de tuberías.',
    category: 'Plomería',
    date: '2024-04-02',
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    reactions: { heart: 7, like: 11, clap: 4, dislike: 0 },
    reviews: [
      { id: 'r3', user: 'Carlos Ruiz', userId: 'c3', comment: 'Rapidísimo y eficiente, lo recomiendo.', rating: 5, date: '2024-04-04' },
    ],
  },
  {
    id: 'pi3',
    expertoId: 'm1',
    title: 'Reparación de fuga en cocina',
    description: 'Detección y reparación de fuga bajo el mesón. Cambio de sifón y sellado de uniones.',
    category: 'Plomería',
    date: '2024-05-10',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80',
    reactions: { heart: 3, like: 8, clap: 2, dislike: 2 },
    reviews: [],
  },
  {
    id: 'pi4',
    expertoId: 'm2',
    title: 'Instalación eléctrica completa',
    description: 'Tablero eléctrico nuevo, circuitos adicionales y puntos de carga para vehículo eléctrico.',
    category: 'Electricidad',
    date: '2024-02-20',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80',
    reactions: { heart: 18, like: 22, clap: 10, dislike: 0 },
    reviews: [
      { id: 'r4', user: 'Ana García', userId: 'c1', comment: 'Trabajo de primera categoría, muy seguro.', rating: 5, date: '2024-02-22' },
    ],
  },
  {
    id: 'pi5',
    expertoId: 'm3',
    title: 'Pintura de departamento completo',
    description: 'Pintura de 3 habitaciones, living y comedor. Preparación de superficies incluida.',
    category: 'Pintura',
    date: '2024-01-18',
    image: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=600&q=80',
    reactions: { heart: 10, like: 15, clap: 8, dislike: 1 },
    reviews: [
      { id: 'r5', user: 'Pedro Martínez', userId: 'c2', comment: 'Quedó hermoso, muy prolijo el trabajo.', rating: 4, date: '2024-01-20' },
    ],
  },
];

export const expertos = [
  {
    id: 'm1',
    nombres: 'Juan',
    apellidos: 'Pérez',
    especialidades: ['Plomería'],
    region: 'Región Metropolitana',
    comuna: 'Santiago',
    rating: 4.9,
    reviews: 120,
    descripcion: 'Plomero con más de 10 años de experiencia en instalaciones y reparaciones.',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: 'm2',
    nombres: 'María',
    apellidos: 'López',
    especialidades: ['Electricidad'],
    region: 'Región Metropolitana',
    comuna: 'Providencia',
    rating: 4.7,
    reviews: 95,
    descripcion: 'Electricista certificada, especialista en instalaciones residenciales y comerciales.',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: 'm3',
    nombres: 'Carlos',
    apellidos: 'Ruiz',
    especialidades: ['Pintura'],
    region: 'Región Metropolitana',
    comuna: 'Ñuñoa',
    rating: 4.5,
    reviews: 70,
    descripcion: 'Pintor profesional con experiencia en acabados de alta calidad.',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
];


